#!/usr/bin/env bash

# This script comes useful when you need to find your Raspberry Pi
# in your local network at home or at friends' home. 
# The IP address might get assigned dinamically and you find yourself
# searching for your Pi's IP address over and over again...

# TODO 
# Fill the configuration file: 'finding-rpi_SAMPLE_.conf'
# with the relevant information regarding the MAC addresses
# of your Raspberry Pi for the:
# - wifi network interface
# - ethernet network interface
# Then rename that file to: 'finding-rpi.conf' in order to
# be sourced into this script.

source finding-rpi.conf

function find_mac () {
   MAC_VALUE=$1
   arp -an | grep -Fe "${MAC_VALUE}" | awk '{ gsub ("\(|\)", "", $2); print "\nINTERFACE ---> " $7 "\nIP ---> " $2 "\nRASPBERRY PI MAC ---> " $4 }'
}

echo -e '\nSearching for the wifi interface...'
find_mac ${RPI_WIFI_MAC}
echo -e '\nSearching for the ethernet interface...'
find_mac ${RPI_ETH0_MAC}
echo -e '\n...done :)\n'
