#!/usr/bin/env node

// this (basic) node.js script generates the name of a git / GitHub branch
// starting from the string provided as a command line input

var args = process.argv.slice(2);
var cleanedArgs = args.map(function(element) {
  cleanedElement = element.replace(/[^\w\s]|_/g, '-');
  // console.log('original element:', element);
  // console.log('cleaned element:', cleanedElement);
  return cleanedElement;
});
var branchName = 'feature/'.concat(cleanedArgs.join('-').toLowerCase())
console.log('branchName:', branchName);

