---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  # https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces
  namespace: restapp
data:
  POSTGRES_PASSWORD: "cGFzczAxCg==" # cGFzczAxCg== # `echo pass01 | base64`
stringData:
  POSTGRES_DB: "postgres"
