---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  # https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-organizing-with-namespaces
  namespace: restapp
spec:
  type: NodePort
  selector:
    app: db-c
  ports:
    - name: postgres
      protocol: TCP
      targetPort: 5432
      port: 5432
